name: nRDB

services:

    api:
        build: ./backend
        depends_on:
            - db
        ports:
            - 3000:3000
        environment:
            MONGODB_URI: ${MONGODB_URI}
        volumes:
            - ./backend:/usr/src/app
        command: node main.js

    db:
        image: mongo:latest
        volumes:
            - mongodb_data:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}

volumes:
    mongodb_data:
