export const municipalities = [
    'Abasolo',
    'Acámbaro',
    'Apaseo el Alto',
    'Apaseo el Grande',
    'Atarjea',
    'Celaya',
    'Comonfort',
    'Coroneo',
    'Cortazar',
    'Cuerámaro',
    'Dolores Hidalgo',
    'Doctor Mora',
    'Guanajuato City',
    'Huanímaro',
    'Irapuato',
    'Jaral del Progreso',
    'Jerécuaro',
    'León',
    'Manuel Doblado',
    'Moroleón',
    'Ocampo',
    'Pénjamo',
    'Pueblo Nuevo',
    'Purísima de Bustos',
    'Romita',
    'Salamanca',
    'Salvatierra',
    'San Diego de la Unión',
    'San Felipe',
    'San Francisco del Rincón',
    'San José Iturbide',
    'San Luis de la Paz',
    'San Miguel de Allende',
    'Santa Catarina',
    'Juventino Rosas',
    'Santiago Maravatío',
    'Silao',
    'Tarandacuao',
    'Tarimoro',
    'Tierra Blanca',
    'Uriangato',
    'Valle de Santiago',
    'Victoria',
    'Villagrán',
    'Xichú',
    'Yuriria'
]
